using AutoMapper;
using Core.DTOS;
using Core.Entities;

namespace Core.Mappers
{
    public class CustomerMappingProfile : Profile
    {
        public CustomerMappingProfile()
        {
            // Enum mappings using explicit type converters to avoid expression-tree overload issues
            CreateMap<CustomerStatus, CustomerStatusDto>()
                .ConvertUsing(new CustomerStatusConverter());

            CreateMap<KycStatus, KycStatusDto>()
                .ConvertUsing(new KycStatusConverter());

            // KYC summary mapping
            CreateMap<KycCase, KycCaseSummaryDto>()
                .ForMember(d => d.Status, opt => opt.MapFrom(s => s.Status))
                .ForMember(d => d.CreatedAt, opt => opt.MapFrom(s => s.CreatedAt))
                .ForMember(d => d.CheckedAt, opt => opt.MapFrom(s => s.CheckedAt))
                .ForMember(d => d.ProviderRef, opt => opt.MapFrom(s => s.ProviderRef));

            // Customer → CustomerResponseDto
            CreateMap<Customer, CustomerResponseDto>()
                .ForMember(d => d.Dob, opt => opt.MapFrom(s => s.Dob))
                .ForMember(d => d.Status, opt => opt.MapFrom(s => s.Status))          // uses enum converter above
                .ForMember(d => d.KycCases, opt => opt.MapFrom(s => s.KycCases));       // uses KycCase → KycCaseSummaryDto


            // --- DTO -> Domain mappings ---
            // Convert DateOnly -> DateTime; set initial status and timestamps.
            CreateMap<CustomerCreateRequestDto, Customer>()
                .ForMember(d => d.CustomerId, opt => opt.Ignore()) // generated by domain
                .ForMember(d => d.Dob, opt => opt.MapFrom(s => s.Dob.ToDateTime(TimeOnly.MinValue)))
                .ForMember(d => d.Status, opt => opt.MapFrom(_ => CustomerStatus.PENDING_KYC))
                .ForMember(d => d.CreatedAt, opt => opt.MapFrom(_ => DateTime.UtcNow))
                .ForMember(d => d.UpdatedAt, opt => opt.Ignore())
                .ForMember(d => d.KycCases, opt => opt.Ignore());
        }

        private sealed class CustomerStatusConverter : ITypeConverter<CustomerStatus, CustomerStatusDto>
        {
            public CustomerStatusDto Convert(CustomerStatus source, CustomerStatusDto destination, ResolutionContext context)
            {
                switch (source)
                {
                    case CustomerStatus.PENDING_KYC:
                        return CustomerStatusDto.PENDING_KYC;
                    case CustomerStatus.VERIFIED:
                        return CustomerStatusDto.VERIFIED;
                    case CustomerStatus.CLOSED:
                        return CustomerStatusDto.CLOSED;
                    default:
                        return CustomerStatusDto.PENDING_KYC;
                }
            }
        }

        private sealed class KycStatusConverter : ITypeConverter<KycStatus, KycStatusDto>
        {
            public KycStatusDto Convert(KycStatus source, KycStatusDto destination, ResolutionContext context)
            {
                switch (source)
                {
                    case KycStatus.PENDING:
                        return KycStatusDto.PENDING;
                    case KycStatus.VERIFIED:
                        return KycStatusDto.VERIFIED;
                    case KycStatus.FAILED:
                        return KycStatusDto.FAILED;
                    default:
                        return KycStatusDto.PENDING;
                }
            }
        }
    }

}
