// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Infrastructure.DbContext;

#nullable disable

namespace dBanking.Infrastructure.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20251230113113_SeedDataCustomertable")]
    partial class SeedDataCustomertable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("dBanking.Core.Entities.AuditRecord", b =>
                {
                    b.Property<Guid>("AuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Action")
                        .HasColumnType("int");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("AfterJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BeforeJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorrelationId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EntityType")
                        .HasColumnType("int");

                    b.Property<Guid>("TargetEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("AuditId");

                    b.HasIndex("EntityType", "TargetEntityId", "Timestamp");

                    b.ToTable("AuditRecords");

                    b.HasData(
                        new
                        {
                            AuditId = new Guid("aaaabbbb-cccc-dddd-eeee-ffff00000001"),
                            Action = 0,
                            Actor = "sub:rahul@aad",
                            AfterJson = "{\"customerId\":\"00112233-4455-6677-8899-aabbccddeeff\",\"status\":\"PENDING_KYC\"}",
                            CorrelationId = "corr-rahul-001",
                            EntityType = 0,
                            TargetEntityId = new Guid("00112233-4455-6677-8899-aabbccddeeff"),
                            Timestamp = new DateTime(2025, 12, 1, 10, 36, 30, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            AuditId = new Guid("aaaabbbb-cccc-dddd-eeee-ffff00000002"),
                            Action = 0,
                            Actor = "sub:rahul@aad",
                            AfterJson = "{\"kycCaseId\":\"aaaaaaaa-bbbb-cccc-dddd-eeeeffff0001\",\"status\":\"PENDING\"}",
                            CorrelationId = "corr-rahul-001",
                            EntityType = 1,
                            TargetEntityId = new Guid("aaaaaaaa-bbbb-cccc-dddd-eeeeffff0001"),
                            Timestamp = new DateTime(2025, 12, 1, 10, 36, 50, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            AuditId = new Guid("aaaabbbb-cccc-dddd-eeee-ffff00000003"),
                            Action = 1,
                            Actor = "system:closure",
                            AfterJson = "{\"customerId\":\"99998888-7777-6666-5555-444433332222\",\"status\":\"CLOSED\"}",
                            BeforeJson = "{\"customerId\":\"99998888-7777-6666-5555-444433332222\",\"status\":\"VERIFIED\"}",
                            CorrelationId = "corr-closure-amit-01",
                            EntityType = 0,
                            TargetEntityId = new Guid("99998888-7777-6666-5555-444433332222"),
                            Timestamp = new DateTime(2025, 12, 5, 14, 0, 20, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("dBanking.Core.Entities.Customer", b =>
                {
                    b.Property<Guid>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("Dob")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("CustomerId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Phone");

                    b.HasIndex("FirstName", "LastName", "Dob");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = new Guid("00112233-4455-6677-8899-aabbccddeeff"),
                            CreatedAt = new DateTime(2025, 12, 1, 10, 30, 0, 0, DateTimeKind.Utc),
                            Dob = new DateOnly(1994, 4, 11),
                            Email = "rahul.sharma@example.com",
                            FirstName = "Rahul",
                            LastName = "Sharma",
                            Phone = "+91-9876543210",
                            Status = 0
                        },
                        new
                        {
                            CustomerId = new Guid("11112222-3333-4444-5555-666677778888"),
                            CreatedAt = new DateTime(2025, 11, 15, 8, 0, 0, 0, DateTimeKind.Utc),
                            Dob = new DateOnly(1992, 6, 25),
                            Email = "neha.kulkarni@example.com",
                            FirstName = "Neha",
                            LastName = "Kulkarni",
                            Phone = "+91-9822001122",
                            Status = 1,
                            UpdatedAt = new DateTime(2025, 11, 20, 9, 15, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            CustomerId = new Guid("99998888-7777-6666-5555-444433332222"),
                            CreatedAt = new DateTime(2025, 10, 10, 11, 45, 0, 0, DateTimeKind.Utc),
                            Dob = new DateOnly(1988, 1, 3),
                            Email = "amit.patil@example.com",
                            FirstName = "Amit",
                            LastName = "Patil",
                            Phone = "+91-9812345678",
                            Status = 2,
                            UpdatedAt = new DateTime(2025, 12, 5, 14, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("dBanking.Core.Entities.KycCase", b =>
                {
                    b.Property<Guid>("KycCaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AcceptedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CheckedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ConsentText")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EvidenceRefsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProviderRef")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("KycCaseId");

                    b.HasIndex("CustomerId", "Status");

                    b.ToTable("KycCases");

                    b.HasData(
                        new
                        {
                            KycCaseId = new Guid("aaaaaaaa-bbbb-cccc-dddd-eeeeffff0001"),
                            AcceptedAt = new DateTime(2025, 12, 1, 10, 35, 0, 0, DateTimeKind.Utc),
                            ConsentText = "I consent to eKYC verification for account onboarding.",
                            CreatedAt = new DateTime(2025, 12, 1, 10, 36, 0, 0, DateTimeKind.Utc),
                            CustomerId = new Guid("00112233-4455-6677-8899-aabbccddeeff"),
                            EvidenceRefsJson = "[\"doc-POI-123\",\"doc-POA-456\"]",
                            Status = 0
                        },
                        new
                        {
                            KycCaseId = new Guid("aaaaaaaa-bbbb-cccc-dddd-eeeeffff0002"),
                            AcceptedAt = new DateTime(2025, 11, 15, 8, 5, 0, 0, DateTimeKind.Utc),
                            CheckedAt = new DateTime(2025, 11, 15, 9, 10, 0, 0, DateTimeKind.Utc),
                            ConsentText = "I consent to eKYC verification for account onboarding.",
                            CreatedAt = new DateTime(2025, 11, 15, 8, 6, 0, 0, DateTimeKind.Utc),
                            CustomerId = new Guid("11112222-3333-4444-5555-666677778888"),
                            EvidenceRefsJson = "[\"doc-POI-777\",\"doc-POA-888\"]",
                            ProviderRef = "kyc-prov-789",
                            Status = 1
                        });
                });

            modelBuilder.Entity("dBanking.Core.Entities.KycCase", b =>
                {
                    b.HasOne("dBanking.Core.Entities.Customer", "Customer")
                        .WithMany("KycCases")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("dBanking.Core.Entities.Customer", b =>
                {
                    b.Navigation("KycCases");
                });
#pragma warning restore 612, 618
        }
    }
}
